#!/bin/bash

set -euo pipefail

# Parse options
QUIET=0
VERBOSE=0
ACTION="show"  # show, set, status
CONFIG_FILE="$HOME/.bitcoin-toolkit-config"
while getopts "qva:c:h" opt; do
    case $opt in
        q) QUIET=1 ;;
        v) VERBOSE=1 ;;
        a) ACTION="$OPTARG" ;;
        c) CONFIG_FILE="$OPTARG" ;;
        h) 
            cat >&2 << 'EOF'
Usage: network.sh [-q] [-v] [-a action] [-c config_file] [network]

Manage Bitcoin network selection for toolkit commands.

Options:
  -q    Quiet mode (suppress informational output)
  -v    Verbose mode (show detailed operations)
  -a    Action: show, set, status (default: show)
  -c    Config file path (default: ~/.bitcoin-toolkit-config)
  -h    Show this help

Actions:
  show      Display current network setting
  set       Set network (requires network argument)
  status    Show network status and API connectivity

Networks:
  mainnet   Bitcoin main network (real funds)
  testnet   Bitcoin test network (test funds only)

Examples:
  network.sh                    # Show current network
  network.sh -a set testnet     # Switch to testnet
  network.sh -a status          # Check network connectivity
  
Environment:
  BITCOIN_NETWORK              # Override config file setting
  
Note: Network setting affects balance.sh and send.sh commands.
EOF
            exit 0
            ;;
        *) exit 1 ;;
    esac
done
shift $((OPTIND-1))

# Logging functions
warn() { [[ $QUIET -eq 0 ]] && echo "Warning: $*" >&2; }
info() { [[ $VERBOSE -eq 1 ]] && echo "Info: $*" >&2; }
die() { echo "Error: $*" >&2; exit 1; }

# Validate action
case "$ACTION" in
    show|set|status) ;;
    *) die "Invalid action: $ACTION (use: show, set, status)" ;;
esac

# Check dependencies
check_dependencies() {
    local missing=()
    if [[ "$ACTION" == "status" ]]; then
        for cmd in curl; do
            command -v "$cmd" >/dev/null 2>&1 || missing+=("$cmd")
        done
        [[ ${#missing[@]} -gt 0 ]] && warn "Missing commands for status check: ${missing[*]}"
    fi
}

# Get current network setting
get_current_network() {
    # Priority: environment variable > config file > default
    if [[ -n "${BITCOIN_NETWORK:-}" ]]; then
        echo "$BITCOIN_NETWORK"
    elif [[ -f "$CONFIG_FILE" ]]; then
        local network
        network=$(grep "^NETWORK=" "$CONFIG_FILE" 2>/dev/null | cut -d= -f2 || echo "")
        echo "${network:-mainnet}"
    else
        echo "mainnet"
    fi
}

# Set network configuration
set_network() {
    local network="$1"
    
    case "$network" in
        mainnet|testnet) ;;
        *) die "Invalid network: $network (use: mainnet, testnet)" ;;
    esac
    
    info "Setting network to: $network"
    
    # Create config directory if needed
    local config_dir
    config_dir=$(dirname "$CONFIG_FILE")
    [[ ! -d "$config_dir" ]] && mkdir -p "$config_dir"
    
    # Update or create config file
    if [[ -f "$CONFIG_FILE" ]]; then
        # Update existing config
        if grep -q "^NETWORK=" "$CONFIG_FILE"; then
            # Replace existing line
            if command -v sed >/dev/null 2>&1; then
                sed -i'' -e "s/^NETWORK=.*/NETWORK=$network/" "$CONFIG_FILE"
            else
                # Fallback method
                grep -v "^NETWORK=" "$CONFIG_FILE" > "${CONFIG_FILE}.tmp" || true
                echo "NETWORK=$network" >> "${CONFIG_FILE}.tmp"
                mv "${CONFIG_FILE}.tmp" "$CONFIG_FILE"
            fi
        else
            # Append to existing config
            echo "NETWORK=$network" >> "$CONFIG_FILE"
        fi
    else
        # Create new config file
        cat > "$CONFIG_FILE" << EOF
# Bitcoin Toolkit Configuration
# Generated by network.sh on $(date)
NETWORK=$network
EOF
    fi
    
    info "Network configuration saved to: $CONFIG_FILE"
    
    # Show current setting
    echo "$network"
}

# Show current network
show_network() {
    local current
    current=$(get_current_network)
    
    if [[ $VERBOSE -eq 1 ]]; then
        cat >&2 << EOF
Network Configuration:
  Current: $current
  Source: ${BITCOIN_NETWORK:+environment}${BITCOIN_NETWORK:-config file}
  Config: $CONFIG_FILE
EOF
    fi
    
    echo "$current"
}

# Test network connectivity
check_network_status() {
    local network
    network=$(get_current_network)
    
    info "Checking $network network connectivity..."
    
    # Test Blockstream API
    local api_url
    if [[ "$network" == "testnet" ]]; then
        api_url="https://blockstream.info/testnet/api/blocks/tip/hash"
    else
        api_url="https://blockstream.info/api/blocks/tip/hash"
    fi
    
    local status="unreachable"
    local latest_block="unknown"
    
    if command -v curl >/dev/null 2>&1; then
        if latest_block=$(curl -s --connect-timeout 5 --max-time 10 "$api_url" 2>/dev/null); then
            if [[ ${#latest_block} -eq 64 ]] && [[ "$latest_block" =~ ^[0-9a-fA-F]+$ ]]; then
                status="connected"
            else
                status="error"
            fi
        fi
    fi
    
    if [[ $VERBOSE -eq 1 ]]; then
        cat >&2 << EOF
Network Status:
  Network: $network
  API Status: $status
  Latest Block: ${latest_block:0:16}...
  Endpoint: $api_url
EOF
    else
        echo "$status"
    fi
}

# Main execution
main() {
    check_dependencies
    
    case "$ACTION" in
        show)
            show_network
            ;;
        set)
            [[ $# -eq 0 ]] && die "Network argument required for set action"
            set_network "$1"
            ;;
        status)
            check_network_status
            ;;
    esac
}

main "$@"